### PR TITLE
feature: use meta_data_updated_at for sorting

### PR DESCRIPTION
**Pull request by phiku**

### CODE REVIEW

**Comment by nimaai** [comment]
apropos datalayer: why not to extend the view? it will save us code and be more performant.

**Comment by phiku** [comment]
will be done later by tom

**Comment by nimaai** [comment]
why not to do it now? it's trivial.

**Comment by nimaai** [comment]
as far as i can see, it would be just one additional line in: https://github.com/Madek/madek-datalayer/blob/master/db/migrate/182_create_media_resources_view.rb#L3-L8

but, one would probably need to make a new migration...

**Comment by phiku** [comment]
http://stackoverflow.com/questions/29047062/postgres-alter-view-add-column

look at the comment at the end... could be not that easy. still easy, but not that easy.

**Comment by nimaai** [comment]
Ok, good to know.

**Pull request merged**
